name: main
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - run: npm t
